### ISSUE TITLE
bug on python 3.6.4 with timegm

### ISSUE THREAD

**Issue by catafest** [Sanjay-B/Pyblox#12]
I think is a common error on python 3 ( see another issue: https://github.com/wit-ai/pywit/issues/116) 
I got this error with this python module :
```
C:\Python364>python.exe
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
 on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyblox3 import Friends
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python364\lib\site-packages\pyblox3\__init__.py", line 16, in <module
>
    from .api.assets import Assets
  File "C:\Python364\lib\site-packages\pyblox3\api\assets.py", line 9, in <modul
e>
    from .http import Http
  File "C:\Python364\lib\site-packages\pyblox3\api\http.py", line 10, in <module
>
    import requests
  File "C:\Python364\lib\site-packages\requests\__init__.py", line 112, in <modu
le>
    from . import utils
  File "C:\Python364\lib\site-packages\requests\utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "C:\Python364\lib\site-packages\requests\_internal_utils.py", line 11, in
 <module>
    from .compat import is_py2, builtin_str, str
  File "C:\Python364\lib\site-packages\requests\compat.py", line 60, in <module>

    from http import cookiejar as cookielib
  File "C:\Python364\lib\http\cookiejar.py", line 41, in <module>
    from calendar import timegm
ImportError: cannot import name 'timegm'
```

**Comment by sbhadr** [comment]
Interesting. It may be a stray ``calendar.pyc`` lurking around. 

Try this and see what it gives you:
``import calendar``
``print calendar.__file__``

This is also caused by having a local ``calendar.py`` file. If this is the case, it might be overriding the actual one.
